### ISSUE TITLE
RSS feed link does not link to the correct page

### ISSUE THREAD

**Issue by Bisaloo** [leonawicz/leonawicz.github.io#1]
Hi,

I saw one of your posts on R-bloggers: https://www.r-bloggers.com/author/matts-r-blog/ but when I clicked on the link to the read the post on your blog, I got a `404` error because it's going to 

https://leonawicz.github.io/post/epubr-0-5-0-cran-release/

instead of 

https://leonawicz.github.io/blog/post/epubr-0-5-0-cran-release/

**Comment by leonawicz** [comment]
Thanks for letting me know. It looks like something I'll have to contact R-Bloggers to get fixed.
